### ISSUE TITLE
merging of two tiffs with different domain

### ISSUE THREAD

**Issue by mattijn** [corteva/rioxarray#357]
Using `rasterio` version 1.2.4 an error is raised on the following code (it still works using `rasterio` version 1.2.1):

```python
import rioxarray as rxr
from rioxarray.merge import merge_arrays

url1 = 'https://github.com/mattijn/datasets/raw/master/cube_nan.tif'
url2 = 'https://github.com/mattijn/datasets/raw/master/clip_cube.tif'

rds1 = rxr.open_rasterio(url1, masked=True)
rds2 = rxr.open_rasterio(url2, masked=True)

merge_arrays([rds1, rds2])
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Miniconda3\envs\myenv\lib\site-packages\rioxarray\merge.py", line 162, in merge_arrays
    merged_data, merged_transform = _rio_merge(
  File "C:\ProgramData\Miniconda3\envs\myenv\lib\site-packages\rasterio\merge.py", line 312, in merge
    dst_window = windows.from_bounds(
  File "C:\ProgramData\Miniconda3\envs\myenv\lib\site-packages\rasterio\windows.py", line 299, in from_bounds
    raise WindowError("Bounds and transform are inconsistent")
rasterio.errors.WindowError: Bounds and transform are inconsistent
```

The bounds are expected to be different and using `rasterio` version 1.2.1 I receive the following output:
```python
merge_arrays([rds1, rds2]).plot()
```
![image](https://user-images.githubusercontent.com/5186265/122752765-a0839180-d291-11eb-963a-837d13a3c814.png)

Some more info on the shape, bounds and transforms of both raster datasets:
```python
rds1.shape, rds1.rio.bounds(), rds1.rio.transform()
```

> ```
> (1, 500, 500))
> ((189050.0, 429650.0, 188550.0, 429150.0),
>  Affine(-1.0, 0.0, 189050.0,
>         0.0, 1.0, 429150.0))
> ```
```python
rds2.shape, rds2.rio.bounds(), rds2.rio.transform()
```

> ```
> (1, 98, 364))
> ((188686.0, 429552.0, 189050.0, 429650.0),
>  Affine(1.0, 0.0, 188686.0,
>         0.0, -1.0, 429650.0))
> ```

I would be very much open on information why my input cannot be parsed anymore after upgrading to `rasterio` 1.2.4.

**Comment by snowman2** [comment]
Related: https://github.com/mapbox/rasterio/issues/2138

**Comment by snowman2** [comment]
```bash
rio merge 'https://github.com/mattijn/datasets/raw/master/cube_nan.tif' 'https://github.com/mattijn/datasets/raw/master/clip_cube.tif' test_merge.tif
```
```
Traceback (most recent call last):
...
  File "~/venv/lib/python3.8/site-packages/rasterio/rio/merge.py", line 61, in merge
    merge_tool(
  File "~/venv/lib/python3.8/site-packages/rasterio/merge.py", line 259, in merge
    dest = np.zeros((output_count, output_height, output_width), dtype=dt)
ValueError: negative dimensions are not allowed
```
```
$ rio --version
1.2.4
$ rio --gdal-version
3.3.0
```

**Comment by mattijn** [comment]
Thanks! This is new information which I can use to dig deeper as well
